learning_templates/basicapp/urls.py
from basicapp import views
from django.conf.urls import url,include

app_name = 'basicapp'

urlpatterns=[
    url(r'^relative/$',views.relative,name="relative"),
    url(r'^other/$',views.other,name="other")

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$',views.index,name="index"),
    path('admin/', admin.site.urls),
    url(r'^basicapp/',include('basicapp.urls')), # ye jo include ke andar likha hai, always put it in brackets so that it is imported automatically
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

def index(request):
    context_dict={'text':'My name is Chetna!', 'number':'21'}
    return render(request, "basicapp/index.html",context_dict)

def other(request):
    return render(request, "basicapp/other.html")

def relative(request):
    return render(request, "basicapp/relative.html")

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav nav-pills navbar-right">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li> &nbsp 
          <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li> &nbsp  &nbsp  &nbsp
          <li><a class="navbar-link" href="{% url 'basicapp:other' %}">OTHER</a></li>
        </ul>
        </div>
        </nav>
      <<div class="container">
        {% block bodyblock %}
        <!-- Anything outside of this block will be inherited -->
        {% endblock %}
        </div>
        </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block bodyblock %}
    <h1>WELCOME TO THE INDEX PAGE!</h1>
    <h1> This is the index.html page! </h1>
    <h1> {{text|cut:'name'}}</h1>
    <h1> {{number}} </h1>
{% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block bodyblock %}
    <h1>WELCOME TO THE OTHERRRR PAGE!</h1>
    <h1> This is an example of template inheritance </h1>
{% endblock %}

learning_templates/templates/basicapp/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RELATIVE PAGE</title>
  </head>
  <body>
    <h1>WELCOME TO THE RELATIVE URL TEMPLATES PAGE!</h1>
    <a href="{% url 'basicapp:other' %}"> The other page </a>
    <br>
    <a href="{% url 'admin:index'%}"> The admin page</a>
    <br>
    <a href="{% url 'index' %}"> The home page </a>

  </body>
</html>